argocd: 
  namespace: argocd
  project: 'opensource'
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: core-data-platform
  sourceRepoURL: 'git@github.com:eclipse-ecsp/ecsp-helm-charts.git'
  targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - RespectIgnoreDifferences=true  


applications:
  hivemq-extension-cluster:
    enabled: true
  kafka:
    enabled: false
  mongodb-sharded:
    enabled: true
  namespace-config:
    enabled: false
  nginx:
    enabled: true
  postgresql:
    enabled: true
  redis:
    enabled: true
  zk:
    enabled: false            
