{{- if (index .Values.applications "notification-sp").enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oss-notification-sp
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: {{ .Values.argocd.project }}
  destination: {{ toYaml .Values.argocd.destination | nindent 4 }}
  syncPolicy: {{ toYaml .Values.argocd.syncPolicy | nindent 4 }}

  source:
    path: {{ .Values.app.definitionPath }}/charts/notification-sp
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}

    helm:
      ignoreMissingValueFiles: true
      values: |
        {{- include "app-of-apps.appValues" (dict "defaultValues" .Values.defaultAppValues.notificationSp "overrides" .Values.notificationSpOverrides "context" $) | nindent 8 }}
{{- end }}